@port = 3000
@host=localhost
@schema=http
@version=v1
@address={{schema}}://{{host}}:{{port}}/{{version}}

get {{schema}}://{{host}}:{{port}}
Accept: application/json
###

GET {{address}}/people HTTP/1.1
Accept: application/json
###

POST {{address}}/people/jane HTTP/1.1
Content-Type: application/json

{
    "values": {
        "name": "Jane Doe",
        "age": 25,
        "city": "New York",
        "country": "USA",
        "occupation": "Software Engineer",
        "hobby": "Reading",
        "favorite_color": "Blue",
        "language": "English",
        "sports": "Soccer",
        "music_genre": "Rock",
        "maried": true
    },
    "etag":1701468834616227574
}

###

GET  {{address}}/people/jane HTTP/1.1
Accept: application/json

###
DELETE {{address}}/people/jane HTTP/1.1
Accept: application/json
